name: build-and-upload

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker build . --no-cache=true --tag uk-cardiff-1.ocir.io/ax39baacthsg/runner-image/ubuntu-act-deb:latest --build-arg COMMIT=$(git rev-parse --short @) --build-arg VERSION=$(git describe --tags)

      - name: Login to OCIR
        run: |
          echo "${{ secrets.OCIR_TOKEN }}" \
            | docker login --username ${{ secrets.OCIR_USERNAME }} --password-stdin uk-cardiff-1.ocir.io

      - name: Upload docker image
        run: |
          docker push uk-cardiff-1.ocir.io/ax39baacthsg/runner-image/ubuntu-act-deb:latest
